### ISSUE TITLE
[BUG] First run causes blackscreen on Pinephone Pro running SailfishOS

### ISSUE THREAD

**Issue by DrYak** [pastillilabs/situations-daemon#1]
When starting Situations for the first time on SailfishOS, it installs, enables and starts the situations-daemon systemd unit, which in turn starts the Situations background service.
(This is normal and expected behaviour).

The Situations background service will immediately apply the profiles.
The default out-of-box profile for "Sleeping" after 21:00 will turn Wifi and Bluetooth off, and set the brightness to 1. 

On a PinePhone Pro, "brightness==1" makes the screen completely dark ("bightness==2" is the lowest setting with the screen still visible and some minimal backlight).

So a fresh installation of Situations on a PinePhone Pro running SailfishOS, if performed after 21:00 will immediately cut the display, and kick your SSH connection, preventing you from fixing it remotely. 

It would be great if:
- at minimum the out-of-the-box demo doesn't Wifi and/or uses a minimum brightness of 2
- at best, have the onboarding process politely asks the user if they want default profiles and/or whether to activate profile switching in Situations or have it paused.

That would avoid people like me needing to reboot the phone into USB MassStorage mode to fix this.

**Comment by hhaveri** [comment]
If you tap through the welcome screens on first install / empty start, you get to choose the default situations to be created. So that's one way to avoid creating the Sleeping situation and thus brightness being set to 1.

Anyway, I'll change it to something safer, say 5 for example. After all, the same issue is (or at least has been) there on Android.

**Comment by DrYak** [comment]
Thank you very much!
